modified:   frontend/src/pages/LoginPage.tsx
Ygg-Drasill/PenaltyThing pull request #32
Opened 2024-09-16 10:59 UTC by TobiasABay

modified:   frontend/src/theme.ts

2024-09-16 11:20 UTC, TobiasABay commented
<img width="926" alt="Skærmbillede 2024-09-16 kl  13 20 30" src="https://github.com/user-attachments/assets/dec52dc5-c646-487c-866e-61e5b3bfdd4e">

2024-09-17 15:05 UTC, alexrefshauge commented
@TobiasABay Hvad med at rykke "sign-up" op på linje med login knappen, så det ikke bruger så meget plads?

2024-09-17 15:12 UTC, alexrefshauge requested changes

2024-09-17 15:12 UTC, alexrefshauge commented on frontend/src/pages/LoginPage.tsx
> +          <Typography avariant="body1" color="white">
```suggestion
          <Typography variant="body1" color="white">
```

2024-09-17 15:12 UTC, alexrefshauge commented on frontend/src/pages/LoginPage.tsx
> +          <Typography variant="body1" color="white">
Kan du ikke bruge temafarverne?

2024-09-18 06:16 UTC, TobiasABay commented on frontend/src/pages/LoginPage.tsx
> +          <Typography variant="body1" color="white">
Altså jo, men de skal skiftes så. De er 💩

2024-09-18 12:41 UTC, alexrefshauge commented on frontend/src/pages/LoginPage.tsx
> +          <Typography variant="body1" color="white">
Så skift dem 😉

2024-09-19 08:38 UTC, alexrefshauge approved these changes

2024-09-19 10:03 UTC, merged